# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim_core_cpp <- function(ancestor_seq_r, init_k0, max_units, max_t, hard_cap, p_local_dup, local_dist, p_distal_dup, distal_dist, p_invert_distal, p_del_chunk, del_dist, p_distal_del, p_conversion, conv_dist, conv_tract, mu_total, p_autocorr_alpha, autocorr_window, autocorr_every, verbose) {
    .Call(`_reCYCLing_sim_core_cpp`, ancestor_seq_r, init_k0, max_units, max_t, hard_cap, p_local_dup, local_dist, p_distal_dup, distal_dist, p_invert_distal, p_del_chunk, del_dist, p_distal_del, p_conversion, conv_dist, conv_tract, mu_total, p_autocorr_alpha, autocorr_window, autocorr_every, verbose)
}

sim_genome_cpp <- function(ancestor_seq_r, K, target_sizes_r, init_k0, max_t, hard_caps_r, p_local_dup, local_dist, p_distal_dup, distal_dist, p_invert_distal, p_del_chunk, del_dist, p_distal_del, p_conversion, conv_dist, conv_tract, p_translocation, transloc_dist, p_invert_transloc, mu_total, p_autocorr_alpha, autocorr_window, autocorr_every, n_generations, size_band, verbose) {
    .Call(`_reCYCLing_sim_genome_cpp`, ancestor_seq_r, K, target_sizes_r, init_k0, max_t, hard_caps_r, p_local_dup, local_dist, p_distal_dup, distal_dist, p_invert_distal, p_del_chunk, del_dist, p_distal_del, p_conversion, conv_dist, conv_tract, p_translocation, transloc_dist, p_invert_transloc, mu_total, p_autocorr_alpha, autocorr_window, autocorr_every, n_generations, size_band, verbose)
}

